spring:
  application:
    name: urlmonitor
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 600000
        max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: mysql
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: urlmonitor
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-53tm81j5h4zbvbma.us.auth0.com/
          audience: https://urlmonitor
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
  task:
    scheduling:
      pool:
        size: 10
urlmonitor:
  distributed-lock:
    lock-key-prefix: "lock:monitored-endpoint:"
  scheduling:
    interval: 10000
  webclient:
    connection-provider:
      name: "webClient"
      max-connections: 200
      max-idle-time: 10
      max-life-time: 1
      pending-acquire-timeout: 60
      pending-acquire-max-count: 100
    http-client:
      response-timeout: 1

logging:
  level:
    org:
      flywaydb:
        core: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html